import './globals.scss'
import {Inter} from 'next/font/google'
import {ReactNode} from 'react'
import {Providers} from '@/components/Providers/Providers'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}: { children: ReactNode }) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Providers>
      <Header/>
      <main>
        {children}
      </main>
      <Footer/>
    </Providers>
    </body>
    </html>
  )
}
