import {ReactNode} from 'react'
import Footer from '../../components/Footer/Footer'
import Header from '../../components/Header/Header'
import {Providers} from '../../components/Providers/Providers'
import {notFound} from 'next/navigation'
import classes from './global.module.scss'

import {NextIntlClientProvider} from 'next-intl'
import {useLocale} from 'next-intl'

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'ru'}, {locale: 'ua'}];
}

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({children, params}: { children: ReactNode, params: { locale: string } }) {
  let messages
  const locale = useLocale()

  try {
    messages = (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }

  if (params.locale !== locale) {
    notFound()
  }

  return (
    <html lang={locale}>
    {/*<body className={inter.className}>*/}
    <body className={classes.body}>
    <NextIntlClientProvider locale={locale} messages={messages}>
      <Providers>
        <header className={classes.header}><Header/></header>
        <main className={classes.main}>{children}</main>
        <footer className={classes.footer}><Footer/></footer>
      </Providers>
    </NextIntlClientProvider>
    </body>
    </html>
  )
}
