import {ReactNode} from 'react'
import Footer from '../../components/Footer/Footer'
import Header from '../../components/Header/Header'
import {Providers} from '../../components/Providers/Providers'
import {useLocale} from 'next-intl'
import {notFound} from 'next/navigation'
import classes from './global.module.scss'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children, params}: { children: ReactNode, params: {locale: string} }) {
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound()
  }

  return (
    <html lang={locale}>
    {/*<body className={inter.className}>*/}
    <body className={classes.body}>
    <Providers>
      <header className={classes.header}><Header/></header>
      <main className={classes.main}>{children}</main>
      <footer className={classes.footer}><Footer/></footer>
    </Providers>
    </body>
    </html>
  )
}
